class RequestCode:
    REGISTRATION = 825
    PUBLIC_KEY_EXCHANGE = 826
    RECONNECTION_ATTEMPT = 827
    FILE_TRANSFER = 828
    VALID_CRC = 900
    INVALID_CRC_RETRY = 901
    INVALID_CRC_DONE = 902


class ResponseCode:
    REGISTRATION_SUCCESS = 1600
    REGISTRATION_FAILURE = 1601
    PUBLIC_KEY_ACCEPTED_AES_EXCHANGE = 1602
    VALID_FILE_WITH_CRC = 1603
    MESSAGE_ACK = 1604  # Could be a response for INVALID_CRC_RETRY, INVALID_CRC_DONE
    RECONNECTION_PUBLIC_KEY_ACCEPTED_AES_EXCHANGE = 1605
    RECONNECTION_REJECTED = 1606
    GENERAL_ERROR = 1607


# Protocol Constants
ENDIAN_TYPE = 'little'
CLIENT_VERSION = SERVER_VERSION = 3
MAX_BYTES_READ = 4096

FILE_NAME_FIELD_SIZE = NAME_FIELD_SIZE = 255
PUBLIC_KEY_SIZE = 160
AES_KEY_SIZE = 32
CLIENT_ID_SIZE = 16
VERSION_SIZE = 1
REQUEST_CODE_SIZE = RESPONSE_CODE_SIZE = 2
PAYLOAD_SIZE_SIZE = 4
CONTENT_SIZE_SIZE = 4
ORIG_FILE_SIZE_SIZE = 4
PACKET_NUM_SIZE = 2
TOTAL_PACKETS_SIZE = 2
CHECKSUM_SIZE = 4  # CRC
FILE_TRANSFER_METADATA_SIZE = (CONTENT_SIZE_SIZE + ORIG_FILE_SIZE_SIZE + PACKET_NUM_SIZE + TOTAL_PACKETS_SIZE
                               + FILE_NAME_FIELD_SIZE)

# Headers formats
REQUEST_HEADER_SIZE = CLIENT_ID_SIZE + VERSION_SIZE + REQUEST_CODE_SIZE + PAYLOAD_SIZE_SIZE
REQUEST_HEADER_FORMAT = f'<{CLIENT_ID_SIZE}s {VERSION_SIZE}s {REQUEST_CODE_SIZE}s {PAYLOAD_SIZE_SIZE}s'

RESPONSE_HEADER_SIZE = VERSION_SIZE + REQUEST_CODE_SIZE + PAYLOAD_SIZE_SIZE
RESPONSE_HEADER_FORMAT = f'<{VERSION_SIZE}s {RESPONSE_CODE_SIZE}s {PAYLOAD_SIZE_SIZE}s'

# Requests payloads formats
REGISTRATION_FORMAT = RECONNECTION_FORMAT = CRC_REQUEST_FORMAT = VALID_CRC_FORMAT = INVALID_CRC_RETRY_FORMAT = \
    INVALID_CRC_DONE_FORMAT = f'{FILE_NAME_FIELD_SIZE}s'
KEY_EXCHANGE_FORMAT = f'{FILE_NAME_FIELD_SIZE}s {PUBLIC_KEY_SIZE}s'
FILE_TRANSFER_METADATA_FORMAT = (f'{CONTENT_SIZE_SIZE}s {ORIG_FILE_SIZE_SIZE}s {PACKET_NUM_SIZE}s '
                                 f'{TOTAL_PACKETS_SIZE}s {FILE_NAME_FIELD_SIZE}s')  # Not including message content

# Responses payloads formats
MESSAGE_ACK_FORMAT = REGISTRATION_SUCCESS_FORMAT = RECONNECTION_REJECTED_FORMAT = f'{CLIENT_ID_SIZE}s'
PUBLIC_KEY_ACCEPTED_AES_EXCHANGE_FORMAT = \
    RECONNECTION_PUBLIC_KEY_ACCEPTED_AES_EXCHANGE_FORMAT = f'{CLIENT_ID_SIZE}s'  # Not including encrypted aes
VALID_FILE_WITH_CRC_FORMAT = f'{CLIENT_ID_SIZE}s {CONTENT_SIZE_SIZE}s {FILE_NAME_FIELD_SIZE}s {CHECKSUM_SIZE}s'
